Simple rectangular tesselation of black and white image

* Method Overview
This package is able to tesselate grayscale images with right angle (90 degrees) rectangles.
Grayscale images have to come with a yaml file describing the meter to pixel resolution.
For instance, check the example maps descrived by the pair of files mrenv/maps/*.yaml and respective mrenv/maps/*.png.
* Note
This repo packages [[https://github.com/joaosalvado/mr_env][mrenv]] on a docker container
* Dependencies
- Docker
- Ubuntu
* Installation
#+begin_src shell
git clone git@github.com:joaosalvado/mr_env.git mrenv
cd thirdparty
git clone git@github.com:jbeder/yaml-cpp.git
#+end_src
* Build
#+begin_src shell
sudo docker build -t mrenv .
#+end_src
* Run Docker Container
This extra running options are required to show opencv images.
#+begin_src shell
docker run -it --rm -e DISPLAY=$DISPLAY \
   -v /tmp/.X11-unix:/tmp/.X11-unix \
   --network=host \
   --volume=$(pwd) \
   --user=$(id -u $USER) \
   --workdir=/mrenv/build/src mrenv
#+end_src
* Examples
/(in progress)/
_insert table of images_
* Licence
<mrenv-pkg simple rectangular tesselation of grayslace images>
Copyright (C) 2022 John Doe

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
